CREATE DATABASE uniproyectos;
USE uniproyectos;
CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombres VARCHAR(50),
    apellidos VARCHAR(50),
    correoPersonal VARCHAR(100),
    contrasena VARCHAR(100),
    numeroCelular INT,
    numeroFijo INT,
    tipoDocumento VARCHAR(20),
    numeroDocumento INT,
    fechaNacimiento DATE,
    paisNacimiento VARCHAR(50),
    ciudadNacimiento VARCHAR(50),
    direccion VARCHAR(255),
    estadoCivil VARCHAR(20),
    sexo CHAR(1),
    perfil VARCHAR(50), -- Profesor Estudiante Publico General
    universidad VARCHAR(100),
    correoInstitucional VARCHAR(100),
    grado VARCHAR(50), -- Sin estudios Primaria Secundaria Tencnico Tecnologo Profesional Especialización Maestria Doctorado
    aceptaTerminos BOOLEAN,
    fechaHoraRegistro TIMESTAMP    
);
CREATE TABLE empresas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    razonSocial VARCHAR(100),
    correo VARCHAR(100),
    contrasena VARCHAR(100),
    numeroFijo INT,
    numeroCelular INT,
    NIT INT,
    tipoEmpresa VARCHAR(50),
    descripcion TEXT,
    area VARCHAR(50),
    tamaño VARCHAR(20),
    sitioWeb VARCHAR(100),
    pais VARCHAR(50),
    direccion VARCHAR(255),
    nombreRepresentanteLegal VARCHAR(100),
    cargoRepresentanteLegal VARCHAR(50),
    correoRepresentanteLegal VARCHAR(100),
    numeroRepresentanteLegal INT,
    aceptaTerminos BOOLEAN,
    fechaHoraRegistro TIMESTAMP
);
CREATE TABLE proyecto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100),
    descripcion TEXT,
    area VARCHAR(50),
    areaTematica VARCHAR(50),
    estado VARCHAR(20),
    ubicacion VARCHAR(100),
    correo VARCHAR(100),
    telefono VARCHAR(15),
    fechaInicio DATE,
    fechaFin DATE,
    fechaRegistro TIMESTAMP,
    informacionAdicional TEXT,
    imagen VARCHAR(100)
);
CREATE TABLE pro_usu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_Proyecto INT,
    id_Usuario INT,
    id_Empresas INT,
    FOREIGN KEY (id_Proyecto) REFERENCES proyecto(id),
    FOREIGN KEY (id_Usuario) REFERENCES usuarios(iD),
    FOREIGN KEY (id_Empresas) REFERENCES empresas(iD)
);
INSERT INTO usuarios (
    nombres,
    apellidos,
    correoPersonal,
    contrasena,
    numeroCelular,
    numeroFijo,
    tipoDocumento,
    numeroDocumento,
    fechaNacimiento,
    paisNacimiento,
    ciudadNacimiento,
    direccion,
    estadoCivil,
    sexo,
    perfil,
    universidad,
    correoInstitucional,
    grado,
    aceptaTerminos,
    fechaHoraRegistro
) VALUES (
    'Admin',
    'Admin',
    'admin@dominio.com',
    'contraseña_admin',
    123456789,
    987654321,
    'TipoDoc',
    1234567890,
    '2000-01-01',
    'País',
    'Ciudad',
    'Dirección Admin',
    'Soltero',
    'M',
    'Admin',
    'Universidad',
    'admin@institucion.com',
    'Maestria',
    1,
    NOW()
);
INSERT INTO empresas (
    nombre,
    razonSocial,
    correo,
    contrasena,
    numeroFijo,
    numeroCelular,
    NIT,
    tipoEmpresa,
    descripcion,
    area,
    tamaño,
    sitioWeb,
    pais,
    direccion,
    nombreRepresentanteLegal,
    cargoRepresentanteLegal,
    correoRepresentanteLegal,
    numeroRepresentanteLegal,
    aceptaTerminos,
    fechaHoraRegistro
) VALUES (
    'Empresa Admin',
    'Razón Social Admin',
    'empresa_admin@dominio.com',
    'contraseña_empresa_admin',
    987654321,
    123456789,
    1234567890,
    'Tipo Empresa',
    'Descripción Empresa Admin',
    'Área Admin',
    'Tamaño Admin',
    'www.empresa-admin.com',
    'País Admin',
    'Dirección Admin',
    'Rep Legal Admin',
    'Cargo Rep Legal Admin',
    'rep_legal_admin@empresa.com',
    1234567890,
    1,
    NOW()
);